version : '3.9'

services :
  # Python Application
  application :
    build : Python
    ports :
      - "8080:8080"
    depends_on :
      - tensor
    networks :
      - app-network
  # TensorFlow Serving
  tensor :
    build : War
    ports :
      - "8501:8501"
    networks :
      - app-network

networks :
  app-network :
    driver : bridge
